project:
  type: book
  output-dir: docs
  preview:
    browser: true
    port: 4321
    watch-inputs: true

book:
  title: "Numerical Analysis 2025"
  subtitle: A Learning Guide
  author:
    - name: Gustav Delius
      email: gustav.delius@york.ac.uk
      affiliation:
      - name: Department of Mathematics, University of York
    - name: Eric Sullivan
      affiliation: Mathematics Faculty at Carroll College

  date: today
  license: CC BY-NC-SA
  repo-url: https://github.com/gustavdelius/NumericalAnalysis2025/
  repo-branch: main
  repo-actions: edit
  favicon: faviconNA.webp
  twitter-card: true
  open-graph: true
  sidebar:
    tools:
      - icon: house-door-fill
        href: https://vle.york.ac.uk/ultra/courses/_111634_1/outline
        text: VLE
      - icon: mortarboard-fill
        href: https://maths.york.ac.uk/moodle/course/view.php?id=2725
        text: Moodle quizzes
      - icon: bug-fill
        href: https://forms.gle/Z8nYvVonGN98L7nv5
        text: Submit a correction
  chapters:
    - index.qmd
    - nmPython.qmd
    - nmNumbers.qmd
    - nmFunctions.qmd
    - nmNonlinear.qmd
    - nmDerivatives.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
    toc-depth: 4

toc: true
number-sections: true
crossref:
  eq-prefix: Eq.
fig-align: left

execute:
  cache: true
  freeze: auto
